title: Unbox Podcast
description: >- 
  Unbox is an independently produced podcast about what it is like to grow up in modern India. Each episode of the show showcases the unique journey of individuals pursuing interesting careers. Gone are the days of everyone becoming an engineer, doctor or lawyer.
url: "https://unboxpod.co"
graph: /img/seo.png

markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

exclude: [.gitignore]

author:
  facebook: TheRatik
  twitter: Ratik96

collections:
  episodes:
    output: true
    permalink: /:collection/:slug
