title: Unbox Podcast
name: Unbox Podcast
locale: en_us
description: >- 
  Unbox is an independently produced podcast about Indians pursuing unconventional careers paths; not letting society box them up in the status-quo.
url: "https://unboxpod.co"
graph: /img/seo.jpg

markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

exclude: [.gitignore]

author:
  facebook: TheRatik
  twitter: Ratik96

collections:
  episodes:
    output: true
    permalink: /:collection/:slug
